version: 1
external_links:
  # See https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/4068
  documentation: "https://kyle-ye.github.io/ScreenShieldKit/documentation/screenshieldkit/"
